Foreground yes
LogTime yes
TCPSocket 3310
TCPAddr 0.0.0.0
User clamav
DatabaseDirectory /var/lib/clamav
StreamMaxLength 105M
MaxFileSize 100M
MaxScanSize 200M
MaxRecursion 16
MaxFiles 10000
AlertExceedsMax yes
ScanArchive yes
